config/routes.rb
Rails.application.routes.draw do
  resources :actionitems do 
    member {post :markcomplete}
    member {post :markincomplete}
  end
  resources :iptodays
  resources :ipyesterdays
  resources :eds
  resources :psycheds
  resources :ors
  root 'home#index'
  resources :home, :only => [:index] do
  	collection {get :archive}
  end
  resources :units 
end

app/models/or.rb
class Or < ActiveRecord::Base
end

app/controllers/ors_controller.rb
class OrsController < ApplicationController
  before_action :set_or, only: [:show, :edit, :update, :destroy]

  # GET /ors
  # GET /ors.json
  def index
    @ors = Or.all
  end

  # GET /ors/1
  # GET /ors/1.json
  def show
  end

  # GET /ors/new
  def new
    @or = Or.new
  end

  # GET /ors/1/edit
  def edit
  end

  # POST /ors
  # POST /ors.json
  def create
    @or = Or.new(or_params)

    respond_to do |format|
      if @or.save
        format.html { redirect_to @or, notice: 'Or was successfully created.' }
        format.json { render :show, status: :created, location: @or }
      else
        format.html { render :new }
        format.json { render json: @or.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ors/1
  # PATCH/PUT /ors/1.json
  def update
    respond_to do |format|
      if @or.update(or_params)
        format.html { redirect_to @or, notice: 'Or was successfully updated.' }
        format.json { render :show, status: :ok, location: @or }
      else
        format.html { render :edit }
        format.json { render json: @or.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ors/1
  # DELETE /ors/1.json
  def destroy
    @or.destroy
    respond_to do |format|
      format.html { redirect_to ors_url, notice: 'Or was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_or
      @or = Or.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def or_params
      params.require(:or).permit(:cases)
    end
end

app/helpers/ors_helper.rb
module OrsHelper
end

app/views/ors/_form.html.erb
<%= form_for(@or) do |f| %>
  <% if @or.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@or.errors.count, "error") %> prohibited this or from being saved:</h2>

      <ul>
      <% @or.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ors/edit.html.erb
<h1>Editing or</h1>

<%= render 'form' %>

<%= link_to 'Show', @or %> |
<%= link_to 'Back', ors_path %>

app/views/ors/index.html.erb
<h1>Listing ors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ors.each do |or| %>
      <tr>
        <td><%= link_to 'Show', or %></td>
        <td><%= link_to 'Edit', edit_or_path(or) %></td>
        <td><%= link_to 'Destroy', or, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Or', new_or_path %>

app/views/ors/new.html.erb
<h1>New or</h1>

<%= render 'form' %>

<%= link_to 'Back', ors_path %>

app/views/ors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_or_path(@or) %> |
<%= link_to 'Back', ors_path %>