config/routes.rb
Rails.application.routes.draw do
  resources :actionitems do 
    member {post :markcomplete}
    member {post :markincomplete}
  end
  resources :iptodays
  resources :ipyesterdays
  resources :eds
  resources :psycheds
  resources :ors
  root 'home#index'
  resources :home, :only => [:index] do
  	collection {get :archive}
  end
  resources :units 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :define_days, only: [:index]
	before_action :generate_todays, only: [:index]
	before_action :def_categories, only: [:index, :archive]
	before_action :check_archive, only: [:index, :archive]
	#Today Index
	def index
		# Define Instance Variables for table generation
		@units = Unit.all
		#Define Today
		@today = Date.today
	end
	def archive
		# Define Instance Variables for table generation
		@units = Unit.all
		@day = params[:date].to_datetime.change(:offset => "-0500")
		@ed = Ed.where({ created_at: @day.noon..(@day.noon + 1.day) }).first
		@psyched = Psyched.where({ created_at: @day.noon..(@day.noon + 1.day) }).first
		@or = Or.where({ created_at: @day.noon..(@day.noon + 1.day) }).first
	end

	private 

		def generate_todays
		#Generate Non-Unit Specific Today Records for ED, Psyched, and OR
			if Ed.where({ created_at: @start..@end }).empty?
				@ed = Ed.create(:level => 0, :census => 0)
			else
				@ed = Ed.where({ created_at: @start..@end }).first
			end
			if Psyched.where({ created_at: @start ..@end }).empty?
				@psyched = Psyched.create(:lmh => 0, :fuh => 0, :stv => 0)
			else
				@psyched = Psyched.where({ created_at: @start..@end }).first
			end
			if Or.where({ created_at: @start..@end }).empty?
				@or = Or.create(:cases => 0)
			else
				@or = Or.where({ created_at: @start..@end }).first
			end
		#Generate Unit specific Today Records for IPToday and IPYesterday
			@units = Unit.all
			@units.each do |unit|
				if unit.iptodays.where({ created_at: @start..@end }).empty?
					unit.iptodays.create()
				end
				if unit.ipyesterdays.where({ created_at: @start..@end }).empty?
					unit.ipyesterdays.create()
				end
			end
		end
		def def_categories
			# Define Instance Variables for each of the 4 categories of action items
			@cat1s = Actionitem.where(:category => "cat1").where(:complete => false)
			@cat2s = Actionitem.where(:category => "cat2").where(:complete => false)
			@cat3s = Actionitem.where(:category => "cat3").where(:complete => false)
			@cat4s = Actionitem.where(:category => "cat4").where(:complete => false)
		end
		def check_archive
			count = 0
			(1..14).each do |i|
   				unless Ed.where({ created_at: i.day.ago.noon..(i.day.ago.noon + 1.day) }).empty?
   					count += 1
   				end
			end
			@archivecount =  count
		end

		def define_days
			# Define Today.noon
			today_noon = Time.zone.now.noon

			if today_noon.future?
				@start = (Time.zone.now.noon - 1.day)
				@end = Time.zone.now.noon
			elsif today_noon.past?
				@start = Time.zone.now.noon
				@end = (Time.zone.now.noon + 1.day)
			end
		end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/archive.html.erb
<h1>Archive - <%= @day.tomorrow.strftime("%A - %B %d, %Y")%></h1>
<!-- Dropdown to select archive date -->
<div class="dropdown">
	<button class="btn btn-info dropdown-toggle" type="button" id="archive_select" data-toggle="dropdown" aria-expanded="true">
	  Archive
	  <span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu" aria-labelledby="archive_select">
		<% (1..@archivecount).each do |d| %>
			<li role="presentation"><%= link_to (d-1).day.ago.strftime("%B %d, %Y"), archive_home_index_path(:date => d.day.ago) %></li>
		<% end -%>
	</ul>
</div><!-- Archive Close --> 
<% unless @ed.nil? %>
	<!-- Row 1 -->
	<div class="row">
	<!-- ED Table -->
		<div class="col-sm-4 col-md-4">
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">ED</h3>
			  </div>
			  <div class="panel-body">
			    <table class="table table-striped">
					<tr>
						<th>Level</th>
						<th>9AM Census</th>
					</tr>
					<tr>
						<td><%= @ed.level %></td>
						<td><%= @ed.census %></td>
					</tr>
				</table>
			  </div>
			</div>
		</div><!-- ED Table Close -->
		<!-- Psych ED Table -->
		<div class="col-sm-4 col-md-4">
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">Psych ED</h3>
			  </div>
			  <div class="panel-body">
			    <table class="table table-striped">
						<tr>
							<th>LMH</th>
							<th>FUH</th>
							<th>ST V's</th>
						</tr>
						<tr>
							<td><%= @psyched.lmh %></td>
							<td><%= @psyched.fuh %></td>
							<td><%= @psyched.stv %></td>
						</tr>
					</table>
			  </div>
			</div>
		</div><!-- Psych ED Table Close -->
		<!-- OR Table -->
		<div class="col-sm-4 col-md-4">
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">OR</h3>
			  </div>
			  <div class="panel-body">
			    <table class="table table-striped">
						<tr>
							<th>Cases</th>
						</tr>
						<tr>
							<td><%= @or.cases %></td>
						</tr>
					</table>
			  </div>
			</div>
		</div><!-- OR Table Close -->
	</div><!-- Row 1 Close -->
	<!-- Row 2 -->
	<div class="row">
		<!-- In Patient - Today Table --> 
		<div class="col-sm-12 col-md-12">
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">In-Patient - Today</h3>
			  </div>
			  <div class="panel-body">
				<table class="table table-striped">
					<tr>
						<th>Unit</th>
						<th>Staffed Capacity</th>
						<th>Actual Census</th>
						<th>Boarders</th>
						<th>Surg Admit</th>
						<th>Planned Admits</th>
						<th>Plan D/C Before Noon</th>
						<th>Plan D/C After Noon</th>
						<th>Adjusted Census</th>
						<th>Precaution Patients #</th>
						<th>1:1 single, group</th>
						<th>LOS > 5 M/S >10 Psych</th>
					</tr>
					<% @units.each do |unit| %>
						<% unitiptoday = unit.iptodays.where({ created_at: @day.noon..(@day.noon + 1.day) }).first %>
						<tr>
							<td><%= unit.name %></td>
							<td><%= unitiptoday.staffedcap %></td>
							<td><%= unitiptoday.actualcensus %></td>
							<td><%= unitiptoday.boarders %></td>
							<td><%= unitiptoday.surgadmit %></td>
							<td><%= unitiptoday.plannedadmit %></td>
							<td><%= unitiptoday.plandcprenoon %></td>
							<td><%= unitiptoday.plandcafternoon %></td>
							<td><%= unitiptoday.adjustedcensus %></td>
							<td><%= unitiptoday.precautionpat %></td>
							<td><%= unitiptoday.singlegroup %></td>
							<td><%= unitiptoday.psych %></td>
						</tr>
					<% end -%>
				</table>
			  </div>
			</div>
		</div><!-- In Patient - Today Table Close -->
	</div><!-- Row 2 Close -->
	<!-- Row 3 --> 
	<div class="row">
		<div class="col-sm-12 col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">In Patient - Yesterday</h3>
				</div>
				<div class="panel-body">
					<table class="table table-striped">
					<tr>
						<th>Unit</th>
						<th>Plan D/C Before Noon</th>
						<th>Actual D/C Before Noon</th>
						<th>Plan D/C After Noon</th>
						<th>Actual D/C After Noon</th>
						<th>Admit HIB</th>
						<th>Longest Wait ED</th>
						<th>Longest Wait PACU</th>
					</tr>
					<% @units.each do |unit| %>
						<% unitipyesterday = unit.ipyesterdays.where({ created_at: @day.noon..(@day.noon + 1.day) }).first %>
						<tr>
							<td><%= unit.name %></td>
							<td><%= unitipyesterday.plandcprenoon %></td>
							<td><%= unitipyesterday.actualdcprenoon %></td>
							<td><%= unitipyesterday.plandcafternoon %></td>
							<td><%= unitipyesterday.actualdcafternoon %></td>
							<td><%= unitipyesterday.admithib %></td>
							<td><%= unitipyesterday.longestwaited %></td>
							<td><%= unitipyesterday.longestwaitpacu %></td>
						</tr>
					<% end -%>
				</table>
				</div>
			</div>
		</div>
	</div><!-- Row 3 Close -->
<% else %>
	<h2>No Data for this day </h2>
<% end -%>

app/views/home/index.html.erb
<h1>
	<% if Time.zone.now.noon.past? %>
		<%= Date.tomorrow.strftime("%A - %B %d, %Y") %>
	<% else %>
		<%= Date.today.strftime("%A - %B %d, %Y") %>
	<% end -%>
</h1>
<div class="btn-group">
	<!-- Dropdown to select archive date -->
		<button class="btn btn-info dropdown-toggle" type="button" id="archive_select" data-toggle="dropdown" aria-expanded="true">
		  Archive
		  <span class="caret"></span>
		</button>
		<ul class="dropdown-menu" role="menu" aria-labelledby="archive_select">
			<% (1..@archivecount).each do |d| %>
				<li role="presentation"><%= link_to d.day.ago.strftime("%B %d, %Y"), archive_home_index_path(:date => d.day.ago) %></li>
			<% end -%>
		</ul>
	<%= link_to "Completed Action Items", actionitems_path, :class => "btn btn-primary", role: "button" %>
</div>
<!-- Row 1 -->
<div class="row">
<!-- ED Table -->
	<div class="col-sm-4 col-md-4 ed">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">ED</h3>
		  </div>
		  <div class="panel-body">
		    <table class="table table-striped">
				<tr>
					<th>Level</th>
					<th>9AM Census</th>
				</tr>
				<tr>
					<td><%= best_in_place @ed, :level, type: :input,:html_attrs => {:tabindex => 1} %></td>
					<td><%= best_in_place @ed, :census, type: :input,:html_attrs => {:tabindex => 2} %></td>
				</tr>
			</table>
		  </div>
		</div>
	</div><!-- ED Table Close -->
	<!-- Psych ED Table -->
	<div class="col-sm-4 col-md-4">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Psych ED</h3>
		  </div>
		  <div class="panel-body">
		    <table class="table table-striped">
					<tr>
						<th>LMH</th>
						<th>FUH</th>
						<th>ST V's</th>
					</tr>
					<tr>
						<td><%= best_in_place @psyched, :lmh, type: :input, :html_attrs => {:tabindex => 3} %></td>
						<td><%= best_in_place @psyched, :fuh, type: :input, :html_attrs => {:tabindex => 4} %></td>
						<td><%= best_in_place @psyched, :stv, type: :input, :html_attrs => {:tabindex => 5} %></td>
					</tr>
				</table>
		  </div>
		</div>
	</div><!-- Psych ED Table Close -->
	<!-- OR Table -->
	<div class="col-sm-4 col-md-4">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">OR</h3>
		  </div>
		  <div class="panel-body">
		    <table class="table table-striped">
					<tr>
						<th>Cases</th>
					</tr>
					<tr>
						<td><%= best_in_place @or, :cases, :html_attrs => {:tabindex => 6} %></td>
					</tr>
				</table>
		  </div>
		</div>
	</div><!-- OR Table Close -->
</div><!-- Row 1 Close -->
<!-- Row 2 -->
<div class="row">
	<!-- In Patient - Today Table --> 
	<div class="col-sm-12 col-md-12">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">In-Patient - Today</h3>
		  </div>
		  <div class="panel-body">
			<table class="table table-striped iptoday">
				<tr>
					<th>Unit</th>
					<th>Staffed Capacity</th>
					<th>Actual Census</th>
					<th>Boarders</th>
					<th>Surg Admit</th>
					<th>Planned Admits</th>
					<th>Planned D/C</th>
					<th>Adjusted Census</th>
					<th>Precaution Patients #</th>
					<th>1:1 single, group</th>
					<th>LOS > 5 M/S >10 Psych</th>
				</tr>
				<tbody>
				<% i = 7 %>
				<% @units.each do |unit| %>
					<% unitiptoday = unit.iptodays.where({ created_at: @start..@end }).first 
					%>
					<tr class="iptodays">
						<td><%= unit.name %></td>
						<% if unit.name == "CDU" %>
							<td class="cdu"><%= best_in_place unitiptoday, :staffedcap, type: :input, :html_attrs => {:tabindex => i} %></td>
						<% else %>
							<td><%= best_in_place unitiptoday, :staffedcap, type: :input, :html_attrs => {:tabindex => i} %></td>
						<% end -%>
						<td><%= best_in_place unitiptoday, :actualcensus, type: :input, :html_attrs => {:tabindex => i + 1} %></td>
						<td><%= best_in_place unitiptoday, :boarders, type: :input, :html_attrs => {:tabindex => i + 2} %></td>
						<td><%= best_in_place unitiptoday, :surgadmit, type: :input, :html_attrs => {:tabindex => i + 3} %></td>
						<td><%= best_in_place unitiptoday, :plannedadmit, type: :input, :html_attrs => {:tabindex => i + 4} %></td>
						<td><%= best_in_place unitiptoday, :plandcafternoon, type: :input, :html_attrs => {:tabindex => i + 5} %></td>
						<td class="adjustedCensus"><span id="adjustedCensus-<%= unitiptoday.id%>">0</span></td>
						<td><%= best_in_place unitiptoday, :precautionpat, type: :input, :html_attrs => {:tabindex => i + 6} %></td>
						<td><%= best_in_place unitiptoday, :singlegroup, type: :input, :html_attrs => {:tabindex => i + 7} %></td>
						<td><%= best_in_place unitiptoday, :psych, type: :input, :html_attrs => {:tabindex => i + 8} %></td>
					</tr>
					<% i += 9 %>
				<% end -%>
				</tbody>
			</table>
		  </div>
		</div>
	</div><!-- In Patient - Today Table Close -->
</div><!-- Row 2 Close -->
<!-- Row 3 --> 
<div class="row">
	<div class="col-sm-12 col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">In Patient - Yesterday</h3>
			</div>
			<div class="panel-body">
				<table class="table table-striped ipyesterday">
				<tr>
					<th>Unit</th>
					<th>Plan D/C</th>
					<th>Actual D/C</th>
					<th>Longest Wait ED</th>
					<th>Longest Wait PACU</th>
				</tr>
				<tbody>
				<% @units.each do |unit| %>
					<% unitipyesterday = unit.ipyesterdays.where({ created_at: @start..@end }).first %>
					<tr class="ipyesterdays">
						<td><%= unit.name %></td>
						<td><%= best_in_place unitipyesterday, :plandcafternoon, type: :input, :html_attrs => {:tabindex => i} %></td>
						<td class="actualDc"><%= best_in_place unitipyesterday, :actualdcafternoon, type: :input, :html_attrs => {:tabindex => i + 1} %></td>
						<td><%= best_in_place unitipyesterday, :longestwaited, type: :input, :html_attrs => {:tabindex => i + 2} %></td>
						<td><%= best_in_place unitipyesterday, :longestwaitpacu, type: :input, :html_attrs => {:tabindex => i + 3} %></td>
					</tr>
					<% i += 4 %>
				<% end -%>
				</tbody>
			</table>
			</div>
		</div>
	</div>
</div><!-- Row 3 Close -->
<!-- Row 4 -->
<div class="row">
	<div class="col-sm-12 col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Are there any open or new safety issues, codes, or events taking place that could have an impact on safety?</h3>
			</div>
			<div class="panel-body">
				<table class="table table-striped">
					<tr>
						<th>Description</th>
						<th>Assigned to</th>
						<th>Due Date</th>
						<th></th>
					</tr>
					<% @cat1s.each do |cat1| %>
						<tr id="ai<%= cat1.id %>">
							<td><%= cat1.description %></td>
							<td><%= cat1.assignedto %></td>
							<td>
								<% unless cat1.duedate.nil? %>
									<%= cat1.duedate.strftime('%B %d, %Y') %>
								<% end %>
							</td>
							<td><%= link_to 'Edit', edit_actionitem_path(cat1, :category => "cat1"), :class => "btn btn-default" %>  <%= link_to 'Delete', actionitem_path(cat1), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %><%= link_to 'Complete', markcomplete_actionitem_path(cat1), :class => "btn btn-success", method: :post, remote: true %></td>
						</tr>
					<% end -%>
				</table>
				<%= link_to "New Action Item", new_actionitem_path(:category => "cat1"), :class => "btn btn-default" %>
			</div>
		</div>
	</div>
</div><!-- Row 4 Close --> 
<!-- Row 5 -->
<div class="row">
	<div class="col-sm-12 col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Are there other open or new issues requiring resolution, such as staffing, compliance, satisfaction, equipment, or IT?</h3>
			</div>
			<div class="panel-body">
				<table class="table table-striped">
					<tr>
						<th>Description</th>
						<th>Assigned to</th>
						<th>Due Date</th>
						<th></th>
					</tr>
					<% @cat2s.each do |cat2| %>
						<tr id="ai<%= cat2.id %>">
							<td><%= cat2.description %></td>
							<td><%= cat2.assignedto %></td>
							<td>
								<% unless cat2.duedate.nil? %>
									<%= cat2.duedate.strftime('%B %d, %Y') %>
								<% end %>
							</td>
							<td><%= link_to 'Edit', edit_actionitem_path(cat2, :category => "cat2"), :class => "btn btn-default" %>  <%= link_to 'Delete', actionitem_path(cat2), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %> <%= link_to 'Complete', markcomplete_actionitem_path(cat2), :class => "btn btn-success", method: :post, remote: true %></td>
						</tr>
					<% end -%>
				</table>
				<%= link_to "New Action Item", new_actionitem_path(:category => "cat2"), :class => "btn btn-default" %>
			</div>
		</div>
	</div>
</div><!-- Row 5 Close --> 
<!-- Row 6 -->
<div class="row">
	<div class="col-sm-12 col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Are there any events, meetings, announcements or rumors that we should be aware of?</h3>
			</div>
			<div class="panel-body">
				<table class="table table-striped">
					<tr>
						<th>Description</th>
						<th>Assigned to</th>
						<th>Due Date</th>
						<th></th>
					</tr>
					<% @cat3s.each do |cat3| %>
						<tr id="ai<%= cat3.id %>">
							<td><%= cat3.description %></td>
							<td><%= cat3.assignedto %></td>
							<td>
								<% unless cat3.duedate.nil? %>
									<%= cat3.duedate.strftime('%B %d, %Y') %>
								<% end %>
							</td>
							<td><%= link_to 'Edit', edit_actionitem_path(cat3, :category => "cat3"), :class => "btn btn-default" %>  <%= link_to 'Delete', actionitem_path(cat3), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %><%= link_to 'Complete', markcomplete_actionitem_path(cat3), :class => "btn btn-success", method: :post, remote: true %></td>
						</tr>
					<% end -%>
				</table>
				<%= link_to "New Action Item", new_actionitem_path(:category => "cat3"), :class => "btn btn-default" %>
			</div>
		</div>
	</div>
</div><!-- Row 6 Close --> 
<!-- Row 7 -->
<div class="row">
	<div class="col-sm-12 col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Are there any follow-up issues for today's Gemba Walks?</h3>
			</div>
			<div class="panel-body">
				<table class="table table-striped">
					<tr>
						<th>Description</th>
						<th>Assigned to</th>
						<th>Due Date</th>
						<th></th>
					</tr>
					<% @cat4s.each do |cat4| %>
						<tr id="ai<%= cat4.id %>">
							<td><%= cat4.description %></td>
							<td><%= cat4.assignedto %></td>
							<td>
								<% unless cat4.duedate.nil? %>
									<%= cat4.duedate.strftime('%B %d, %Y') %>
								<% end %>
							</td>
							<td><%= link_to 'Edit', edit_actionitem_path(cat4, :category => "cat4"), :class => "btn btn-default" %>  <%= link_to 'Delete', actionitem_path(cat4), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %><%= link_to 'Complete', markcomplete_actionitem_path(cat4), :class => "btn btn-success", method: :post, remote: true %></td>
						</tr>
					<% end -%>
				</table>
				<%= link_to "New Action Item", new_actionitem_path(:category => "cat4"), :class => "btn btn-default" %>
			</div>
		</div>
	</div>
</div><!-- Row 7 Close --> 
<div class="row">
	<div class="col-sm-12 col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Would anyone like to recognize a team member for an exceptional performance?</h3>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12 col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Are there any other issues that have not been addressed?</h3>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12 col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Does anyone need to meet with anyone after the huddle?</h3>
			</div>
		</div>
	</div>
</div>