config/routes.rb
Rails.application.routes.draw do
  resources :actionitems do 
    member {post :markcomplete}
    member {post :markincomplete}
  end
  resources :iptodays
  resources :ipyesterdays
  resources :eds
  resources :psycheds
  resources :ors
  root 'home#index'
  resources :home, :only => [:index] do
  	collection {get :archive}
  end
  resources :units 
end

app/models/ed.rb
class Ed < ActiveRecord::Base
end

app/controllers/eds_controller.rb
class EdsController < ApplicationController
  before_action :set_ed, only: [:show, :edit, :update, :destroy]

  # GET /eds
  # GET /eds.json
  def index
    @eds = Ed.all
  end

  # GET /eds/1
  # GET /eds/1.json
  def show
  end

  # GET /eds/new
  def new
    @ed = Ed.new
  end

  # GET /eds/1/edit
  def edit
  end

  # POST /eds
  # POST /eds.json
  def create
    @ed = Ed.new(ed_params)

    respond_to do |format|
      if @ed.save
        format.html { redirect_to @ed, notice: 'Ed was successfully created.' }
        format.json { render :show, status: :created, location: @ed }
      else
        format.html { render :new }
        format.json { render json: @ed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eds/1
  # PATCH/PUT /eds/1.json
  def update
    respond_to do |format|
      if @ed.update(ed_params)
        format.html { redirect_to @ed, notice: 'Ed was successfully updated.' }
        format.json { render :show, status: :ok, location: @ed }
      else
        format.html { render :edit }
        format.json { render json: @ed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eds/1
  # DELETE /eds/1.json
  def destroy
    @ed.destroy
    respond_to do |format|
      format.html { redirect_to eds_url, notice: 'Ed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ed
      @ed = Ed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ed_params
      params.require(:ed).permit(:level, :census)
    end
end

app/helpers/eds_helper.rb
module EdsHelper
end

app/views/eds/_form.html.erb
<%= form_for(@ed) do |f| %>
  <% if @ed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ed.errors.count, "error") %> prohibited this ed from being saved:</h2>

      <ul>
      <% @ed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eds/edit.html.erb
<h1>Editing ed</h1>

<%= render 'form' %>

<%= link_to 'Show', @ed %> |
<%= link_to 'Back', eds_path %>

app/views/eds/index.html.erb
<h1>Listing eds</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eds.each do |ed| %>
      <tr>
        <td><%= link_to 'Show', ed %></td>
        <td><%= link_to 'Edit', edit_ed_path(ed) %></td>
        <td><%= link_to 'Destroy', ed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ed', new_ed_path %>

app/views/eds/new.html.erb
<h1>New ed</h1>

<%= render 'form' %>

<%= link_to 'Back', eds_path %>

app/views/eds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ed_path(@ed) %> |
<%= link_to 'Back', eds_path %>