config/routes.rb
Rails.application.routes.draw do
  resources :actionitems do 
    member {post :markcomplete}
    member {post :markincomplete}
  end
  resources :iptodays
  resources :ipyesterdays
  resources :eds
  resources :psycheds
  resources :ors
  root 'home#index'
  resources :home, :only => [:index] do
  	collection {get :archive}
  end
  resources :units 
end

app/models/psyched.rb
class Psyched < ActiveRecord::Base
end

app/controllers/psycheds_controller.rb
class PsychedsController < ApplicationController
  before_action :set_psyched, only: [:show, :edit, :update, :destroy]

  # GET /psycheds
  # GET /psycheds.json
  def index
    @psycheds = Psyched.all
  end

  # GET /psycheds/1
  # GET /psycheds/1.json
  def show
  end

  # GET /psycheds/new
  def new
    @psyched = Psyched.new
  end

  # GET /psycheds/1/edit
  def edit
  end

  # POST /psycheds
  # POST /psycheds.json
  def create
    @psyched = Psyched.new(psyched_params)

    respond_to do |format|
      if @psyched.save
        format.html { redirect_to @psyched, notice: 'Psyched was successfully created.' }
        format.json { render :show, status: :created, location: @psyched }
      else
        format.html { render :new }
        format.json { render json: @psyched.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /psycheds/1
  # PATCH/PUT /psycheds/1.json
  def update
    respond_to do |format|
      if @psyched.update(psyched_params)
        format.html { redirect_to @psyched, notice: 'Psyched was successfully updated.' }
        format.json { render :show, status: :ok, location: @psyched }
      else
        format.html { render :edit }
        format.json { render json: @psyched.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /psycheds/1
  # DELETE /psycheds/1.json
  def destroy
    @psyched.destroy
    respond_to do |format|
      format.html { redirect_to psycheds_url, notice: 'Psyched was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_psyched
      @psyched = Psyched.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def psyched_params
      params.require(:psyched).permit(:lmh, :fuh, :stv)
    end
end

app/helpers/psycheds_helper.rb
module PsychedsHelper
end

app/views/psycheds/_form.html.erb
<%= form_for(@psyched) do |f| %>
  <% if @psyched.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@psyched.errors.count, "error") %> prohibited this psyched from being saved:</h2>

      <ul>
      <% @psyched.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/psycheds/edit.html.erb
<h1>Editing psyched</h1>

<%= render 'form' %>

<%= link_to 'Show', @psyched %> |
<%= link_to 'Back', psycheds_path %>

app/views/psycheds/index.html.erb
<h1>Listing psycheds</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @psycheds.each do |psyched| %>
      <tr>
        <td><%= link_to 'Show', psyched %></td>
        <td><%= link_to 'Edit', edit_psyched_path(psyched) %></td>
        <td><%= link_to 'Destroy', psyched, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Psyched', new_psyched_path %>

app/views/psycheds/new.html.erb
<h1>New psyched</h1>

<%= render 'form' %>

<%= link_to 'Back', psycheds_path %>

app/views/psycheds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_psyched_path(@psyched) %> |
<%= link_to 'Back', psycheds_path %>